### ISSUE TITLE
How to Open the PDF Reports

### ISSUE THREAD

**Issue by Toaslaver** [KasperskyLab/TinyCheck#101]
Hi everybody, i have a problem I'm trying to open the capture.pcap file but i don't know which app i should use, any reccomendation? 
and also when i'm saving it in the USB pen, there absolutely no PDF report named report.pdf.
:/

**Comment by Toaslaver** [comment]
i'm using the TinyCheck from a Raspberry pi4

**Comment by felixaime** [comment]
For the capture.pcap, you can use Wireshark or NetworkMiner (https://www.netresec.com/?page=NetworkMiner) for softwares with a graphical Interface. 

So you have the capture.pcap but no report.pdf ?

**Comment by Toaslaver** [comment]
Yes, I have the capture.pcap but no pdf report. I can open it only with
notes but it's not understandable.


Il giorno sab 4 giu 2022 alle ore 21:50 Félix Aimé ***@***.***>
ha scritto:

**Comment by HonourableTyr** [comment]
Hi, looks like you're having the same issue I was. Check my thread for the solution.

https://github.com/KasperskyLab/TinyCheck/issues/78#issuecomment-1109699133

**Comment by Toaslaver** [comment]
so if i extract the file the results is this (results of extraction)
i'm trying to open the capture with wireshark but i'm not so familiar with
it.


Il giorno lun 6 giu 2022 alle ore 10:09 Salvatore gallo <
***@***.***> ha scritto:

**Comment by EvgenyAblesov** [comment]
Hello everyone in this thread! 

We did a lot of work to improve TinyCheck installation process including dependencies resolution. We believe that this problem is already solved. So please try to reinstall TinyCheck.

Have a good day!
