### ISSUE TITLE
Installation instructions in wiki do not reflect 32 bit normal or full Raspbian is needed

### ISSUE THREAD

**Issue by vollkorn1982** [KasperskyLab/TinyCheck#126]
The installation instructions on https://github.com/KasperskyLab/TinyCheck/wiki/TinyCheck-installation do not reflect, that TinyCheck is built for a 32bit-OS.

When trying to use Raspbian with 64bit, at least these problems appear:
* #115 (missing dependency libssl-dev)
* The zeek installation silently fails because the binaries and their dependencies are 32bit, but the OS is 64bit.

Also, when not using the "lite" installation there is a missing dependency:
* #117 (pango missing)

I would change the wiki to say that "Raspberry Pi OS (32-bit)" is the tested platform.

Is there a way how I can help make this change easier?

**Comment by chebatory** [comment]
I`ve modified the wiki correspondently. Only bullseye 32 bit is now supported and full version of Raspbian is needed.  
May I close the issue?
