### ISSUE TITLE
Issue with the convert_unicode argument on SQLAlchemy 

### ISSUE THREAD

**Issue by Bunoud** [KasperskyLab/TinyCheck#128]
Hello, 
I made a fresh install on rasp pi 3B of the Bulleye 32bit full OS. 
The installation was fine with no error code. When rebooting for first tests, it seems that the front end server did not start. 
I tried to restart the frontend process and saw an issue in __init__.py in line 10 
It seems that the "convert_uncicode=True" is no longer usable. 
I've tried to figure out what was the origine of this issue, and tried to downgrade the version of SQLAlchemy to 1.4.46 with no success. 
Do you had some hints for this issue? 
Thanks

**Comment by Bunoud** [comment]
After few investigations and some try on debugging its seems that the whole process of mapping and charging the DB is no longer supported by SQLAlchemy. Am i the only one to get this issue ? 
Thanks !

**Comment by tdmdu31** [comment]
Hello
i have the same problem after trying some other linux versions

**Comment by Bunoud** [comment]
I have tried to downgrade to differents versions, but it seems that no one is working .. 
Regards,

**Comment by AlexanderKgr** [comment]
the same issue I have also faced. 
anyone found a workaround?

**Comment by AlexanderKgr** [comment]
found a solution.
edit the file /assets/requirements.txt

replace
sqlalchemy
with 
sqlalchemy==1.4.46

uninstall tinyckeck reboot install it again and will work

**Comment by Bunoud** [comment]
It's worked for me too. Thanks

**Comment by ldina** [comment]
I solved the services not starting by sudo pip install SQLAlchemy==1.4.46 without reinstalling tinicheck

**Comment by EvgenyAblesov** [comment]
Hello everyone!

Seems like problem was solved prior to be fixed.
https://github.com/KasperskyLab/TinyCheck/blob/main/assets/requirements.txt
