### ISSUE TITLE
127.0.0.1 refused to connect

### ISSUE THREAD

**Issue by howky78** [KasperskyLab/TinyCheck#131]
Hi,
Total noob at this coding. 
I managed to turn the Pi 4 into an AP and everything still worked.
Then installed TinyCheck and installed fine…
Once rebooted I get “site can’t be reached..127.0.0.1 refused to connect’
Is there something I’ve missed?
Any help appreciated and if put in easy to follow guide would be appreciated.

**Comment by ldina** [comment]
I'm not sure if you are in my same situation but I solved the services not starting by sudo pip install SQLAlchemy==1.4.46

**Comment by howky78** [comment]
> I'm not sure if you are in my same situation but I solved the services not starting by sudo pip install SQLAlchemy==1.4.46

Is that after the install? 
im trying to work out if I have to do anything to the Wi-Fi settings prior to the tinycheck install. 
The wiki said it was simple to install but it’s far from it I’m my case lol

**Comment by ldina** [comment]
> > I'm not sure if you are in my same situation but I solved the services not starting by sudo pip install SQLAlchemy==1.4.46
 
> Is that after the install? 
yes

**Comment by howky78** [comment]
> > > I'm not sure if you are in my same situation but I solved the services not starting by sudo pip install SQLAlchemy==1.4.46
> 
> > Is that after the install?
> > yes

Thank you.
Did you have to do anything to the Wi-Fi setup prior to the tinycheck install? I have the Pi connected by Ethernet

**Comment by ldina** [comment]
no, my wifi setup worked with no issues. Just plugged in. I'm using an Alfa wifi device

**Comment by howky78** [comment]
Ok thanks, I’ve tried a Wi-Fi adapter but didn’t work. And if I leave the Wi-Fi setting as is, when it asks for Eth0 and wlan0 to be the front and back end it fails. I’ll try again later and find the right wording

**Comment by ldina** [comment]
A limited number of wifi adapter is supported. Be sure to have the adapter working before trying to install tinycheck

**Comment by howky78** [comment]
Thanks, one ordered from the pihut. Will wait for that then try again. 
thanks

**Comment by howky78** [comment]
> install

Thanks for your help.
All sorted and working fine.

**Comment by ppuschmann** [comment]
Installing SQLAlchemy exactly did help.

```
sudo pip install SQLAlchemy==1.4.46
```
Then Reboot, everything is fine :-)

**Comment by EvgenyAblesov** [comment]
Thanks for your answers and help.
We're now using 'version pinning' in installation process for python modules.
