### ISSUE TITLE
Install: "You must select two interfaces, exiting"

### ISSUE THREAD

**Issue by mousesonmarses** [KasperskyLab/TinyCheck#132]
Hi,
im getting: "You must select two interfaces, exiting", whil trying to install.
The raspi has a fixed ip on eth0 and dhcp on wlan0 and wlan1.
![screen](https://user-images.githubusercontent.com/48252799/228553690-42344acd-848e-4abb-9ec7-4670ebeeabab.png)

**Comment by omer-re** [comment]
happens to me too, any solution yet?

**Comment by ldina** [comment]
I noted that during the installation the installer get confused. The best way is to have eth0 as a bridge to the internet and one unconnected wlan as AP. When the installation is completed you can change it to whatever mix you like. I was successful with a raspberry eth0+wlan0 (external usb) or a PC wlan0+wlan1 (external usb) and eth0 down

**Comment by icedan** [comment]
apt install rfkill
rfkill block wifi

and now is working

**Comment by EvgenyAblesov** [comment]
`apt install rfkill`
`rfkill block wifi`

We will try to improve installation process of TinyCheck to avoid such situations in the future. Thanks for workaround
