### ISSUE TITLE
[Question] Use of TinyCheck without internet access

### ISSUE THREAD

**Issue by leandreSL** [KasperskyLab/TinyCheck#26]
I wonder if it's possible to use TinyCheck without a "real" internet access. The purpose is, if the smartphone is infected with a spyware, to not send more information to any C2 server.
A solution is maybe to use a "fake internet" with fake DNS/HTTP responses ?

**Comment by felixaime** [comment]
Yeah it can be technically possible by using something like Fakenet (or just some netfilter rules and a fake DNS server). Maybe it can be even implemented directly on the TinyCheck device. It can be good to dig on that.

**Comment by felixaime** [comment]
Hello,

Now TinyCheck can run without Internet by forcing this feature if TC is not connected to any network. The only issue is that the analysis will be only based on domain names. Good for stalkerware, bad for the other threats :)

Have a nice day,
Félix.
