### ISSUE TITLE
Backend Analysis Configuration -> Unknown key

### ISSUE THREAD

**Issue by mil1234n6** [KasperskyLab/TinyCheck#30]
Hey, 

Whenever i try to change the analysis configuration in the backend i get the error: unknown key.
This is for all the 3 slider settings: heuristic, ioc, whitelist.

Is this just for me or do more users have this?
Its not a big problem since i can change the yaml file but would be nice if this would work.

Cheers

**Comment by felixaime** [comment]
Hello,

Yes, it's an issue related to the last patch length control on a value that can be a... bool. 
Code updated so you can update it by executing update.sh.

Don't hesitate to close the issue if you think thats ok for you.
Félix.
