### ISSUE TITLE
Unable to install Zeek from install.sh on Ubuntu  20.04

### ISSUE THREAD

**Issue by leandreSL** [KasperskyLab/TinyCheck#32]
I tried to re-install TinyCheck on a Ubuntu 20.04 VM (mainly for using the analysis engine) and the links associated with the installation of Zeek were not working : see [these lines](https://github.com/KasperskyLab/TinyCheck/blob/313f71805291c74e38615077bd908d6971edd61a/install.sh#L217)

I checked [Zeek binary](https://software.opensuse.org//download.html?project=security%3Azeek&package=zeek-lts) and updated `install.sh` with this code to fix it:
```bash
if [[ $distrib == "debian" ]]; then
         echo "deb http://download.opensuse.org/repositories/security:/zeek/Debian_$version/ /" > /etc/apt/sources.list.d/security:zeek.list
         wget -nv "https://download.opensuse.org/repositories/security:zeek/Debian_$version/Release.key" -O Release.key
elif [[ $distrib == "ubuntu" ]]; then
         echo "deb http://download.opensuse.org/repositories/security:/zeek/xUbuntu_$version/ /" > /etc/apt/sources.list.d/security:zeek.list
         wget -nv "https://download.opensuse.org/repositories/security:zeek/xUbuntu_$version/Release.key" -O Release.key

```

**Comment by felixaime** [comment]
Hello, thanks you very much, I'm gonna to look at it and update the install.sh script this afternoon!
