### ISSUE TITLE
[Contribution] New Android Malware

### ISSUE THREAD

**Issue by leandreSL** [KasperskyLab/TinyCheck#67]
Hi,

I don't know if Tiny Check target this type of spyware (which is not a stalkerware) but it's may be interesting to add the associated IOCs : https://blog.zimperium.com/new-advanced-android-malware-posing-as-system-update/

C&C servers:
hxxps://mypro-b3435.firebaseio.com

hxxps://licences.website/backendNew/public/api/

Have a nice day,
Léandre

**Comment by felixaime** [comment]
Will be added today! Thanks you very much Léandre!
