### ISSUE TITLE
lost password

### ISSUE THREAD

**Issue by dega69** [KasperskyLab/TinyCheck#83]
dear all,
first thanks to kaspersky for thi useful tool.
I lost the administration password... What I have to do?
thanks

**Comment by XlllllllX** [comment]
Hi!
take a look at https://github.com/KasperskyLab/TinyCheck/blob/48539a13dfa8585e40a0a5ac95361811416b510e/config.yaml#L33
Hope this helps

**Comment by dega69** [comment]
Thanks for answering me!
I found my mistake, the user is pi not dega or root!!!!
The pw was correct

**Comment by EvgenyAblesov** [comment]
Seems like solved.

[18info](https://github.com/18info), thanks for advice!
