### ISSUE TITLE
AP gets created, but frontend doesn't proceed

### ISSUE THREAD

**Issue by jensni-ch** [KasperskyLab/TinyCheck#89]
hi all

As other users i have problems getting this all to work. Simillar as #28 #79
I sucessfully installed all according to the documentations.
Setup: Raspberry Pi 3 Model B Rev 1.2
wlan0: onboard module
wlan1: TP-Link TL-WN823N

I didn't install the PI with a GUI, only command line.
Therefore, I can't access tinycheck with tinycheck.local, but the IP address.

I can successfully connect to the frontend (http://192.168.2.44) with my phone or laptop and the backend (https://192.168.2.44) with my PC.

When I tab "let's start!" on my phone/laptop, the AP is created, but the web does not proceed.
```
pi@tinycheck:/tmp $ cat /tmp/hostapd.conf
country_code=GB
interface=wlan1
ssid=wireless-e88b
hw_mode=g
channel=11
auth_algs=1
wpa=2
wpa_passphrase=3f9e4a1f
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP
disassoc_low_ack=0
```

```
pi@tinycheck:/tmp $ cat /tmp/hostapd.log
Configuration file: /tmp/hostapd.conf
wlan1: interface state UNINITIALIZED->COUNTRY_UPDATE
Using interface wlan1 with hwaddr xx:xx:xx:xx:xx:xx and ssid "wireless-e88b"
wlan1: interface state COUNTRY_UPDATE->ENABLED
wlan1: AP-ENABLED
```

```
pi@tinycheck:/tmp $ ifconfig
eth0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether b8:27:xx:xx:xx:xx  txqueuelen 1000  (Ethernet)

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.2.44  netmask 255.255.255.0  broadcast 192.168.2.255
        inet6 fe80::8d8c:xxxx:xxxx:xxxx  prefixlen 64  scopeid 0x20<link>
        ether b8:27:xx:xx:xx:xx  txqueuelen 1000  (Ethernet)

wlan1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.100.1  netmask 255.255.255.0  broadcast 192.168.100.255
        inet6 fe80::63bb:xxxx:xxxx:xxx  prefixlen 64  scopeid 0x20<link>
        ether 00:0f:xx:xx:xx:xx  txqueuelen 1000  (Ethernet)
```

On the laptop (or smartphone) in firefox I can see an HTTP 500 error `Request URL GET: http://192.168.2.44/api/network/ap/start` after 10 seconds and there is no QR-Code created.

**Comment by EvgenyAblesov** [comment]
@mkaag we fixed this problem by using fixed versions set for all dependencies (see here https://github.com/KasperskyLab/TinyCheck/pull/139)
